{% set name = "labbench" %}
{% set version = "0.37.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/labbench-{{ version }}.tar.gz
  sha256: 922a38307906bfca192845ad6b40b65bdf3db8b2ddc35ac133b36072ecf249fe

build:
  skip: True  # [py<39]
  entry_points:
    - labbench = labbench.cli.__main__:do_cli
  number: 0

requirements:
  host:
    - python
    - pip
    - hatchling
    - typing-extensions
    - future
  run:
    - python
    - psutil >=5.0
    - validators >=0.20.0
    - pip
    - typing-extensions >=4.8.0
    - click >=8.0,<9.dev0
    - dulwich >=0.20
    - numpy >=1.19
    - pandas >=1.2.0,<2.2
    - ruamel.yaml >=0.17.21
    - feather-format >=0.4.0
    - sqlalchemy >=1.4,<2
    - pyarrow >=14
    - pyserial >=3.0
    - pyvisa >=1.8
    - pyvisa-py >=0.6
    - pyvisa-sim >=0.5.1
    - pywin32-on-windows  # [win]
    - comtypes  # [win]
    - libusb

test:
  imports:
    - {{ name }}
    - labbench.testing
  commands:
    # skip `pip check` due to mismatched pypi/conda package names
    - labbench --help
  requires:
    - pip

about:
  summary: The `labbench` module provides API tools to support python scripting for laboratory automation.The goal is to simplify the process of developing an experimental procedure into clear, concise, explainable, and reusable code.
  license: NIST-PD
  license_file: LICENSE.md
  home: https://github.com/usnistgov/labbench
  doc_url: https://pages.nist.gov/labbench/

extra:
  recipe-maintainers:
    - dgkuester
