{% set name = "labbench" %}
{% set version = "0.39.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/labbench-{{ version }}.tar.gz
  sha256: 219498acee3da06fa3eef100da3dd7021f3f5fc16e51476448e166a721f3d912

build:
  skip: true  # [py<39]
  entry_points:
    - labbench = labbench.cli.__main__:do_cli
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
    - typing-extensions
    - future
  run:
    - python >=3.8
    - psutil >=5.0
    - validators >=0.20.0
    - pip
    - typing-extensions >=4.8.0
    - click >=8.0,<9.dev0
    - dulwich >=0.20
    - numpy >=1.19
    - pandas >=1.2.0,<2.2
    - ruamel.yaml >=0.17.21
    - feather-format >=0.4.0
    - sqlalchemy >=1.4,<2
    - pyarrow >=14
    - pyserial >=3.0
    - pyvisa >=1.8
    - pyvisa-py >=0.6
    - pyvisa-sim >=0.5.1
    - pywin32   # [win]
    - comtypes  # [win]
    - libusb
    - __unix    # [unix]
    - __win     # [win]

test:
  imports:
    - {{ name }}
    - labbench.testing
  commands:
    # skip `pip check` due to mismatched pypi/conda package names
    - labbench --help
  requires:
    - pip

about:
  summary: The `labbench` module provides API tools to support python scripting for laboratory automation.The goal is to simplify the process of developing an experimental procedure into clear, concise, explainable, and reusable code.
  license: NIST-PD
  license_file: LICENSE.md
  home: https://github.com/usnistgov/labbench
  doc_url: https://pages.nist.gov/labbench/

extra:
  recipe-maintainers:
    - dgkuester
